import Head from "next/head";
import Navbar from "@/fragments/Navbar";
import Hero from "@/fragments/Hero";
import Divisi from "@/fragments/Content/divisi";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar></Navbar>
      <Hero></Hero>
      <Divisi></Divisi>
    </>
  );
}
