import Head from "next/head";
import Hero from "@/components/fragments/Hero";
import Divisi from "@/components/fragments/Content/divisi";
import FeedbackForm from "@/components/fragments/FeedbackForm";
import Footer from "@/components/fragments/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero></Hero>
      <Divisi></Divisi>
      <FeedbackForm></FeedbackForm>
      <Footer />
    </>
  );
}
